name: blogs
services:
    blogs:
        cpu_shares: 90
        command: []
        container_name: blogs
        deploy:
            resources:
                limits:
                    memory: "8438939648"
        image: blogs:latest
        labels:
            icon: https://png.pngtree.com/png-vector/20230304/ourmid/pngtree-colorful-blog-speech-bubble-vector-png-image_6633021.png
        network_mode: bridge
        ports:
            - mode: ingress
              target: 5678
              published: "5678"
              protocol: tcp
        restart: unless-stopped
        volumes:
            - type: bind
              source: /home/sid/Projects/blogs/md
              target: /app/md
              bind:
                create_host_path: true
networks:
    default:
        name: blogs_default
x-casaos:
    author: self
    category: self
    hostname: ""
    icon: https://png.pngtree.com/png-vector/20230304/ourmid/pngtree-colorful-blog-speech-bubble-vector-png-image_6633021.png
    index: /
    is_uncontrolled: false
    port_map: "5678"
    scheme: http
    title:
        custom: 'Blogs '
